### ISSUE TITLE
git tag : x.y.z and pep440 not compatible ?

### ISSUE THREAD

**Issue by nyue** [mtkennerly/dunamai#42]
Hi,

  We are migrating from versioneer.

  We tag our repo with the number format of X.Y.Z

```
$ git tag
1.2.3
```

However, when querying with dunamai, I get a pattern error

I have tried both
```
dunamai from git
```
and
```
dunamai from git --style pep440
```

Both times, I got the following message
```
Pattern '(?x)                                                        (?# ignore whitespace)
    ^v((?P<epoch>\d+)!)?(?P<base>\d+(\.\d+)*)                   (?# v1.2.3 or v1!2000.1.2)
    ([-._]?((?P<stage>[a-zA-Z]+)[-._]?(?P<revision>\d+)?))?     (?# b0)
    (\+(?P<tagged_metadata>.+))?$                               (?# +linux)' did not match any tags from ['1.2.3']
```

In addition, I would like to retrieve the version not on the commandline but within the setup.py so I would need to make the query with the dunamai module via the API itself.

Cheers

**Comment by nyue** [comment]
Thanks for the clarification @mtkennerly 
Are you able to share an example pattern ? I tried but have problem creating the required `base` grouping that it is expecting.

**Comment by mtkennerly** [comment]
One option would be to copy the regex from the source code and just remove the `v` from the start of line 38:

https://github.com/mtkennerly/dunamai/blob/ab262fbce43b3beab91e2f2a40298ded5412508c/dunamai/__init__.py#L36-L41

Here's a simple regex with the bare minimum that's required:

```python
pattern = r"^(?P<base>\d+(\.\d+)*)"
```

**Comment by nyue** [comment]
That works. Thank you.
