### ISSUE TITLE
Documentation for output substitutions

### ISSUE THREAD

**Issue by mfulgo** [mtkennerly/dunamai#50]
Two thoughts around documentation...

Something I've struggled with a couple times here is knowing what options are available for substitutions in the custom output format and knowing what exactly each one mean. The list is available [in the help](https://github.com/mtkennerly/dunamai/blob/master/dunamai/__main__.py#L56) (`dunamai from any --help`), but it'd be nice if it was also available here in the README, with an explanation of what each substitution means.

It's also unclear from the documentation as to whether or not substitutions are always included or if some substitutions would be omitted if the distance from a base tag is 0. (If not, that might be an interesting feature - defining an optional portion of a custom format...)

I'd be happy to make a PR to update the docs if you're interested.

**Comment by mtkennerly** [comment]
Hi! I've added [a section](https://github.com/mtkennerly/dunamai#custom-formats) to the README to cover this. Thanks for the feedback :)

**Comment by mfulgo** [comment]
Looks great, thanks!
