### ISSUE TITLE
Possibly misleading vcs check message for git

### ISSUE THREAD

**Issue by bartekwojcicki** [mtkennerly/dunamai#58]
Git introduced [stricter repository ownership checks][1]. When the check fails, `git status` fails:
```
$ git status
fatal: detected dubious ownership in repository at '/path/redacted'
To add an exception for this directory, call:
	git config --global --add safe.directory /path/redacted
```

When using dunamai (via poetry-dynamic-versioning), this is replaced with:
`This does not appear to be a Git project`

Having the original error message or having this specific error mapped to a more detailed error message would make debugging this easier. Happy to add a pull merge request with preferred approach.

PS. Thank you for your packages, poetry-dynamic-versioning makes my life easier 👍 

[1]: https://github.blog/2022-04-18-highlights-from-git-2-36/#stricter-repository-ownership-checks

**Comment by mtkennerly** [comment]
Thanks for reporting this! I went with mapping it to a more specific error.

> PS. Thank you for your packages, poetry-dynamic-versioning makes my life easier 👍

I'm happy to hear that :)
