### ISSUE TITLE
Wrong version being reported

### ISSUE THREAD

**Issue by Silvanoc** [mtkennerly/dunamai#63]
Using dunamai to obtain the last tag of project [LinkML](https://github.com/linkml/linkml) doesn't work correctly on a GitLab pipeline (locally runs as expected, even when using the same container image being used in the pipeline).

I'm letting `git tag` show me all the tags sorted (`--sort`) by all the possible keys and the result is always the same (`1.5.2.xyz` as of now). But when I use `dunamai from git` to get that version I obtain `1.5.0.xyz` 😮.

I've already checked that the tags are annotated and that the initial commit is not tagged and empty.

I can reproduce it, but only in the pipeline, therefore debugging is a bit cumbersome... Any hints on how to diagnose the issue?

**Comment by Silvanoc** [comment]
I found out something more. A branch that was created from a commit following `v1.5.0` (before v1.5.1) has been merged after `v1.5.2` and `git log --topo-order` appears to be taking that branch in the topological order instead of the main one that is being taken on my machine. Why?

It is a shallow clone, if I unshallow it, then **it works**!

IMO dunamai should report at least a warning (and should be added to the documentation) that due to some issues with `git log --topo-order`, dunamai might provide unexpected results.

**Comment by Silvanoc** [comment]
`git rev-parse --is-shallow-repository` tells you if it's a shallow repository, dunamai could check it and report a warning.

**Comment by mtkennerly** [comment]
The next release will include an automatic check:

```console
$ dunamai from git
Warning: This is a shallow repository, so Dunamai may not produce the correct version.
0.0.0.post8.dev0+8e8b1e1

$ echo $?
0

$ dunamai from git --strict
This is a shallow repository, so Dunamai may not produce the correct version.

$ echo $?
1
```

**Comment by Silvanoc** [comment]
Will the `poetry-dynamic-versioning` [option `strict`](https://github.com/mtkennerly/poetry-dynamic-versioning/blob/9f53714d1a1e9585af48d0ac44edd32d7833e49b/README.md?plain=1#L193) also result in the same check?

**Comment by mtkennerly** [comment]
Yes, it will :) `poetry-dynamic-versioning` will just need an update to show the warning, but the `--strict` error will happen automatically.

**Comment by mtkennerly** [comment]
Dunamai v1.17.0 and poetry-dynamic-versioning v0.22.0 are out now and include these changes.

**Comment by Silvanoc** [comment]
It's great how quickly you've addressed it! 💯
