### ISSUE TITLE
dunamai 1.18.0 silently does not produce version with `--strict` in CI

### ISSUE THREAD

**Issue by danielgafni** [mtkennerly/dunamai#66]
I recently upgraded `dunamai` to 1.1.18 and it started failing in my GitLab CI. 

1. It started displaying this error: `Detected Git repository, but failed because of dubious ownership`, so I quickly added `git config --global --add safe.directory '*'` to my `Dockerfile` as the first stackoverflow answer suggested. Not sure if this is relevant to the issue. 
2. `dunamai from git --style pep440 --strict` *in CI* is executing with exit code 0, but doesn't produce any stdout. It runs normally *locally*. 

I'm using Docker executor with GitLab so everything is running inside Docker.

**Comment by mtkennerly** [comment]
Hi! Some questions for you:

* Is there any output on stderr?
* Does it work without `--strict`?
* Do you have `GIT_DEPTH` set to 0, or some equivalent way of fetching the full history?

**Comment by mtkennerly** [comment]
I'm going to close this for now, but if you get a chance to check the above details, please let me know.
