### ISSUE TITLE
Git version detection fails if `log.excludeDecoration = refs/tags` set in git config

### ISSUE THREAD

**Issue by natehardison** [mtkennerly/dunamai#67]
We have some engineers that have `log.excludeDecoration = refs/tags` set in their `.gitconfig` since we have some repos with a large number of tags.

These same engineers would attempt to install a Python package that uses `poetry-dynamic-versioning` and `dunamai` and get a failure like `RuntimeError: Unable to determine commit offset for ref refs/tags/v1.0.0  in data: {}`.

After some digging, we found that with tags excluded from the logs, `_GitRefInfo.from_git_tag_topo_order` can't find any tags, leading to the `RuntimeError`.

I *think* a fix could be to switch to use the `git rev-list` plumbing command instead of the `git log` porcelain command. Happy to take a crack at a PR if that approach makes sense.

**Comment by mtkennerly** [comment]
Thanks for reporting this! Adding `--decorate-refs=refs/tags/` to the command should fix this. (Actually, I had removed that argument in v1.5.2 for compatibility with older Git versions, but I can just make it conditional on the version.)

**Comment by natehardison** [comment]
Even simpler! Thanks.
