### ISSUE TITLE
Visual Studio Code Workspace Settings file is missing ending `}`

### ISSUE THREAD

**Issue by rlaphoenix** [mtkennerly/dunamai#72]
https://github.com/mtkennerly/dunamai/blob/8301b9a87994f9a7a6dcf66056b91ee130a25ae8/.vscode/settings.json#L11

**Comment by mtkennerly** [comment]
Did you run into some error locally? I'm not seeing an issue in the file. There's a `{}` pair on lines 1 and 14, and there's a `[]` pair on lines 9 and 11.
