### ISSUE TITLE
Remove python dependency upper bound

### ISSUE THREAD

**Issue by yajo** [mtkennerly/dunamai#74]
Python dependency has an upper bound:
https://github.com/mtkennerly/dunamai/blob/8a16c30124a1421d62ee8d492f77e3a63b01bd9c/pyproject.toml#L24

https://iscinumpy.dev/post/bound-version-constraints/ explains why this is bad.

Would you mind to please remove that and just use `python = ">=3.5"`?

Thanks!

**Comment by mtkennerly** [comment]
While I don't agree with that article's points about Semantic Versioning, I do agree that:

* Python itself doesn't follow Semantic Versioning
* The flat nature of site-packages makes it hard to deal with conflicting version bounds

While doing some research, I also found these discussions helpful:

* https://discuss.python.org/t/requires-python-upper-limits/12663
* https://github.com/python-poetry/poetry/issues/6884

I'll relax the bounds to use `>=`.
