### ISSUE TITLE
Add option for detecting only changed files as dirty

### ISSUE THREAD

**Issue by m1stadev** [mtkennerly/dunamai#82]
Hi, would it be possible for an option to be added that doesn't detect untracked files as dirty?

Perhaps a flag could be added to [`Version.from_git()`](https://github.com/mtkennerly/dunamai/blob/c42b85b224ad53967a1a562a53aa83ee5bb90374/dunamai/__init__.py#L987) (`skip_untracked`?) that skips over [this section](https://github.com/mtkennerly/dunamai/blob/c42b85b224ad53967a1a562a53aa83ee5bb90374/dunamai/__init__.py#L1135-L1138) of code.

I'd be willing to PR this if necessary.

**Comment by mtkennerly** [comment]
Hi! This will be included in the next release :)
