### ISSUE TITLE
request: format substitutions for `{major}`, `{minor}` and `{patch}`

### ISSUE THREAD

**Issue by zevisert** [mtkennerly/dunamai#92]
Hi! Thanks for dunamai - it's my favourite tool for dynamic versioning, by a long shot and I've tried a few others! 

It would be even greater if dunamai could provide the format substitutions from the title! I imagine the semver logic dunamai already uses could provide those.

My use case is with tagging docker images during a build, it'd be really nice to be able to build three tags at once, like for tag `v1.2.3` as:
- `my-registry/some-image:1`
- `my-registry/some-image:1.2`
- `my-registry/some-image:1.2.3`;

I can't quite create those tags directly with dunamai, since there's only the `{base}` format. I'd like to be able to do something like `dunamai from git --format='{major}.{minor}'` to make the `1.2` tag, for instance.

**Comment by mtkennerly** [comment]
I'm glad you've found Dunamai helpful \:D

This is now available in [v1.23.0](https://github.com/mtkennerly/dunamai/releases/tag/v1.23.0).
